name: Deno release

on:
  workflow_run:
    workflows: ["Deno test"]
    types:
      - completed
    status:
      - success
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.
      - name: Publish package
        run: deno publish
